name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Clear Terraform Cache
      run: rm -rf .terraform .terraform.lock.hcl

    - name: Initialize Terraform
      run: terraform init

    - name: Make check_and_apply.sh executable
      run: chmod +x backend-iac-repo/iac/check_and_apply.sh

    - name: Check and Apply Terraform
      if: github.ref == 'refs/heads/main'
      run: backend-iac-repo/iac/check_and_apply.sh