name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0
        
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Terraform Init
      working-directory: backend-iac-repo/iac
      run: terraform init

    - name: Terraform Validate
      working-directory: backend-iac-repo/iac
      run: terraform validate

    - name: Terraform Plan
      working-directory: backend-iac-repo/iac
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      working-directory: backend-iac-repo/iac
      run: backend-iac-repo/iac/check_and_apply.sh
